#!/bin/bash
# Generate the report
echo -e "\nSystem Report generated by $USERNAME, $DATE_TIME\n"
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s):"
echo "$DISK_INFO"
echo "Video: $VIDEO_CARD"
echo
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS_LOGGED_IN"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo

